cluster:
  name: "docker-cluster"
  initial_master_nodes: ["master_node"]

node:
  name: "master_node"

network:
  host: "_site_"

http:
  port: 9200

discovery:
  seed_hosts: ["elasticsearch","node_1"]

xpack:
  license.self_generated.type: trial
  security.enabled: false
  monitoring.collection.enabled: true
