version: "3.8"

volumes:
  mysql_data:
  elasticsearch_volume:

services:
  mysqldb:
    build: backend/db
    env_file:
      - "backend/db/db.env"
    ports:
      - "8989:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend/was
    command: >
      bash -c "python wait_mysql.py &&
               python setup_es.py &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend/was:/app
    depends_on:
      mysqldb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./observe/prometheus/config/:/etc/prometheus/
    ports:
      - 9090:9090
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3100:3100
    volumes:
      - ./observe/grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always

  elasticsearch:
    build:
      context: backend/elastic_search/
      args:
        ELK_VERSION: 7.16.3
    restart: always
    volumes:
      - ./backend/elastic_search/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch_volume:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672" # Default Port
      - "15672:15672" # For UI
    expose:
      - "15672"

  celery_worker:
    container_name: celery_worker
    build:
      context: ./backend/was
      dockerfile: dockerfile
    volumes:
      - ./backend/was:/backend
    ports: []
    depends_on:
      - rabbitmq
      - redis
      - backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "python wait_mysql.py &&
                    celery -A was worker --loglevel=info"

  kibana:
    container_name: kibana
    image: kibana:7.16.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  nginx:
    build: backend/nginx
    ports:
      - 80:80
    volumes:
      - ./backend/nginx/nginx:/etc/nginx
    depends_on:
      - backend

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:latest
#    container_name: cadvisor
#    ports:
#      - 8090:8090
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    depends_on:
#      - redis
#    command:
#      - '-port=8090'