version: "3"

services:
  backend:
    build: ./backend
    command: [ "python","manage.py","runserver","0.0.0.0:8080" ]
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  #  frontend:
  #    build: ./frontend
  #    command: ["npm", "start"]
  #    ports:
  #      - 3000:3000
  #    volumes:
  #      - ./frontend:/app
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"