version: "3"

volumes:
  mysql_data:
  elastic_search:

services:
  mysqldb:
    build: ./db
    env_file:
      - "./db/db.env"
    ports:
      - "8989:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
  backend:
    build: ./backend
    command: >
      bash -c "python wait_mysql.py &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - mysqldb
  elasticsearch:
    container_name: elastic_search
    build:
      context: ./elastic_search
      args:
        ELK_VERSION: 7.16.3
    restart: always
    volumes:
      - ./elastic_search/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elastic_search:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
#  nginx:
#    build: ./nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx:/etc/nginx
#    depends_on:
#      - mysqldb
#      - backend
  #  frontend:
  #    build: ./frontend
  #    command: ["npm", "start"]
  #    ports:
  #      - 3000:3000
  #    volumes:
  #      - ./frontend:/app